<template>
  <VApp>
    <TheBanner></TheBanner>
    <TheNav></TheNav>
    <VMain>
      <NuxtPage></NuxtPage>
    </VMain>
    <TheFooter></TheFooter>
    <CookiesWarning></CookiesWarning>
  </VApp>
</template>
