<template>
  <VApp>
    <VContainer>
      <TheNav></TheNav>
    </VContainer>
    <VMain>
      <NuxtPage></NuxtPage>
    </VMain>
    <VContainer>
      <TheFooter></TheFooter>
    </VContainer>
  </VApp>
</template>
